### ISSUE TITLE
AttributeError: 'list' object has no attribute 'cpu'

### ISSUE THREAD

**Issue by shikha4444** [machine-perception-robotics-group/attention_branch_network#13]
Thank you for the code, I am getting this error in running the imagenet.py on my 3 class data, If I am commenting the line 326-327 and 331-352 than the code runs fine and I got the classification results. Now I want to visualize the sample images, So, I have uncommented the lines. I am getting the below error. 

  File "imagenet.py", line 326, in test
    c_att = attention.data.cpu()
AttributeError: 'list' object has no attribute 'data'

When the same command is applied on inputs i.e.,      
d_inputs = inputs.data.cpu()
 d_inputs = d_inputs.numpy()

I am not getting any errors. 
Please help.

**Comment by shikha4444** [comment]
Another observation is inputs size is  "torch.Size([40, 3, 224, 224])" whereas attention size is "[torch.Size([40, 1, 14, 14]), torch.Size([40, 256, 14, 14]), torch.Size([40, 256, 14, 14])]"

**Comment by utsavdshah** [comment]
Hi @shikha4444 

Were you able to resolve this issue? I am facing similar problem.

**Comment by saahilislam** [comment]
I am facing the same problem, did anyone solve this?

**Comment by LiuXiang199x** [comment]
> I am facing the same problem, did anyone solve this?

Change it to tensor then use .cpu()

**Comment by d-kleine** [comment]
> > I am facing the same problem, did anyone solve this?
> 
> Change it to tensor then use .cpu()

Just for completion, it would be
```python
torch.tensor(attention).detach().cpu().numpy()
```

`attention` is a list, whereas `inputs` seems to be a tensor already (and subsequently, `d_inputs` will be as well). Therefore, `attention` needs to be converted to a tensor in order to move it to cpu (and converted it to an an numpy array). See [here](https://stackoverflow.com/questions/53467215/convert-pytorch-cuda-tensor-to-numpy-array) for further information.
